services:
  script:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: python
      args:
        WORKDIR: ${WORKDIR}
    networks:
      - deleteme_akellner
networks:
  deleteme_akellner:
    external: true
